apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web-app-deployment-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-web-app-2
  template:
    metadata:
      labels:
        app: simple-web-app-2
    spec:
      containers:
        - name: simple-web-app-2
          image: trstringer/simple-web-app:1.0.1
          ports:
            - containerPort: 80